image: ridibooks/php:7.0

variables:
  COMPOSER_HOME: $CI_PROJECT_DIR/.composer
  GIT_SUBMODULE_STRATEGY: normal

cache:
  key: composer
  paths:
    - .composer/cache/

.php-unit: &php-unit
  stage: test
  script:
    - composer install
    - vendor/bin/phpunit --coverage-text

stages:
  - build
  - test

composer:
  stage: build
  script:
    - composer validate
    - composer install

phpcs:
  stage: test
  script:
    - composer install
    - vendor/bin/phpcs --standard=./ruleset.xml

phpunit-7.0:
  image: ridibooks/store-php-test:7.0
  <<: *php-unit


phpunit-7.1:
  image: ridibooks/store-php-test:7.1
  <<: *php-unit

phpunit-7.2:
  image: ridibooks/store-php-test:7.2
  <<: *php-unit
